version: 2.1

jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: |
          npx playwright install // https://github.com/microsoft/playwright/issues/4033#issuecomment-877099201
          npm i && npm test

workflows:
  build:
    jobs:
      - test
